services:
  - type: web
    name: kalendarz-backend
    # USUWAMY LINIĘ 'runtime: java' - Render sam wykryje Javę na podstawie zawartości folderu
    repo: https://github.com/Zemby1996/Interactive-Calendar # <-- UPEWNIJ SIĘ, ŻE TO JEST GŁÓWNY ADRES URL TWOJEGO REPOZYTORIUM
    plan: free
    
    # Ustawienia budowania i uruchamiania
    rootDir: backend/interactive-calendar-backend # <-- TA ŚCIEŻKA JEST TERAZ NAJWAŻNIEJSZA
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/interactive-calendar-backend-0.0.1-SNAPSHOT.jar" # Pamiętaj, aby sprawdzić, czy ta nazwa pliku .jar jest poprawna
    
    envVars:
      - key: SERVER_PORT
        value: 10000 # Render wymaga, aby aplikacje nasłuchiwały na porcie 10000