services:
  - type: web
    name: kalendarz-backend
    runtime: docker
    repo: https://github.com/Zemby1996/Interactive-Calendar
    plan: free
    autoDeploy: true
    branch: main

    # --- POPRAWKA JEST TUTAJ ---
    # Ustawienia dla budowania z Dockerfile
    dockerContext: backend/interactive-calendar-backend # <-- MÓWIMY DOCKEROWI, GDZIE MA ZACZĄĆ
    dockerfilePath: backend/interactive-calendar-backend/Dockerfile
    
    # Sekcja envVars pozostaje bez zmian
    envVars:
      - key: SERVER_PORT
        value: 10000