services:
  - type: web
    name: kalendarz-backend
    # UWAGA: Zamiast 'runtime', 'buildCommand', itd., teraz określamy ustawienia dla Dockera
    dockerfilePath: backend/interactive-calendar-backend/Dockerfile
    plan: free
    autoDeploy: true
    
    # Zmienne środowiskowe nadal ustawiasz w panelu Render w zakładce 'Environment'
    envVars:
      - key: SERVER_PORT
        value: 10000